export enum feedbackFields {
  serviceStars = 'Степень удовлетворенности получения Услуги',
  workStars = 'Степень удовлетворенности работой специалистов МЭЦ',
  MECStars = 'Оценка работы МЭЦ по предоставлению Услуги',
  contractNumber = 'Номер контракта',
  contractWith = 'С кем заключен контракт',
  contractItem = 'Товар/Услуга',
  contractDate = 'Дата',
  country = 'Страна',
  contractSumm = 'Сумма контракта',
}

export const configFeadBack = {
  rating: [
    {
      id: 1,
      title: 'Степень удовлетворенности получения Услуги',
      value: 0,
    },
    {
      id: 2,
      title: 'Степень удовлетворенности работой специалистов МЭЦ',
      value: 0,
    },
    {
      id: 3,
      title: 'Оценка работы МЭЦ по предоставлению Услуги',
      value: 0,
    },
  ],
  сheckbox: [
    {
      id: 5,
      title: 'Благодаря услуге удалось заключить контракт',
      type: 'сheckbox',
      subtitle: '* Опционально',
      value: false,
    },
  ],
  input: [
    {
      id: 6,
      title: 'Номер контракта',
      value: '',
      type: 'text',
      onFocus: 'text',
    },
    {
      id: 7,
      title: 'С кем заключен контракт',
      value: '',
      type: 'text',
      onFocus: 'text',
    },
    {
      id: 8,
      title: 'Товар/Услуга',
      value: '',
      type: 'text',
      onFocus: 'text',
    },
    {
      id: 9,
      title: 'Дата',
      value: '',
      type: 'text',
      onFocus: 'date',
    },
    // {
    //   id: 10,
    //   title: 'Страна',
    //   value: '',
    //   type: 'text',
    //   onFocus: 'text',
    // },
    {
      id: 11,
      title: 'Сумма контракта',
      value: '',
      type: 'text',
      onFocus: 'text',
    },
  ],
  DocumentUploader: [
    {
      id: 12,
      name: 'Согласие',
      fields: [
        {
          name: 'Подтверждаю достоверность и полноту сведений, предоставленных в Заявке и необходимых документов',
          description: null,
          parameterInApi: 'p8296714',
          fieldType: {
            id: 2418,
            name: 'Флажок',
            code: null,
            dictionaries: [],
          },
          required: true,
          signatureRequired: false,
          inner: false,
          url: null,
          signatures: [],
          maxSignaturesCount: null,
          digitalStorageType: {
            name: 'Подтверждаю достоверность и полноту сведений, предоставленных в Заявке и необходимых документов',
            outerId: null,
            outerName: null,
            fileFormats: null,
            fileSizeMaxByte: 0,
          },
          visibility: true,
          isUserFill: true,
          readOnly: false,
          measureServiceParamValueGroup: null,
          stage: {
            order: 2,
            name: '3',
            description: 'Заверения и согласия',
            group: null,
          },
          inputMask: null,
        },
        {
          name: 'Не имеет задолженности по уплате налогов, сборов, страховых взносов, пеней, штрафов, процентов во внебюджетные фонды и бюджеты бюджетной системы Российской Федерации на день подачи Заявки на сумму не более 100 000 (ста тысяч) рублей',
          description: null,
          parameterInApi: 'p8296896',
          fieldType: {
            id: 2418,
            name: 'Флажок',
            code: null,
            dictionaries: [],
          },
          required: true,
          signatureRequired: false,
          inner: false,
          url: null,
          signatures: [],
          maxSignaturesCount: null,
          digitalStorageType: {
            name: 'Не имеет задолженности по уплате налогов, сборов, страховых взносов, пеней, штрафов, процентов во внебюджетные фонды и бюджеты бюджетной системы Российской Федерации на день подачи Заявки на сумму не более 100 000 (ста тысяч) рублей',
            outerId: null,
            outerName: null,
            fileFormats: null,
            fileSizeMaxByte: 0,
          },
          visibility: true,
          isUserFill: true,
          readOnly: false,
          measureServiceParamValueGroup: null,
          stage: {
            order: 2,
            name: '3',
            description: 'Заверения и согласия',
            group: null,
          },
          inputMask: null,
        },
        {
          name: 'Уровень владения английским языком сотрудника Заявителя, направляемого на обучение, не ниже Intermediate (самостоятельное владение, B1)',
          description: null,
          parameterInApi: 'p8296973',
          fieldType: {
            id: 2418,
            name: 'Флажок',
            code: null,
            dictionaries: [],
          },
          required: true,
          signatureRequired: false,
          inner: false,
          url: null,
          signatures: [],
          maxSignaturesCount: null,
          digitalStorageType: {
            name: 'Уровень владения английским языком сотрудника Заявителя, направляемого на обучение, не ниже Intermediate (самостоятельное владение, B1)',
            outerId: null,
            outerName: null,
            fileFormats: null,
            fileSizeMaxByte: 0,
          },
          visibility: true,
          isUserFill: true,
          readOnly: false,
          measureServiceParamValueGroup: null,
          stage: {
            order: 2,
            name: '3',
            description: 'Заверения и согласия',
            group: null,
          },
          inputMask: null,
        },
        {
          name: 'ННастоящим выражаю согласие на обработку моих персональных данных, предусмотренную частью 3 статьи 3 Федерального закона от 27.07.2006 № 152-ФЗ «О персональных данных» (далее – Федеральный закон от 27.07.2006 № 152-ФЗ), при предоставлении АНО «МЭЦ» в соответствии с Положением о порядке предоставления Услуги «Организация образовательного курса «Английский язык для внешнеэкономической деятельности». Мне известно, что предоставленные мною персональные данные будут подвергнуты обработке, предусмотренной Федеральным законом от 27.07.2006 № 152-ФЗ, при этом публикация моих персональных данных будет произведена АНО «МЭЦ» в соответствии с действующим законодательством. Мне известно, что настоящее согласие действует бессрочно. В случае отзыва согласия на обработку персональных данных, АНО «МЭЦ» вправе продолжить обработку персональных данных без моего согласия в соответствии с частью 2 статьи 9, пунктом 4 части 1 статьи 6 Федерального закона от 27.07.2006 № 152-ФЗ.',
          description: null,
          parameterInApi: 'p8297011',
          fieldType: {
            id: 2418,
            name: 'Флажок',
            code: null,
            dictionaries: [],
          },
          required: true,
          signatureRequired: false,
          inner: false,
          url: null,
          signatures: [],
          maxSignaturesCount: null,
          digitalStorageType: {
            name: 'НННастоящим выражаю согласие на обработку моих персональных данных, предусмотренную частью 3 статьи 3 Федерального закона от 27.07.2006 № 152-ФЗ «О персональных данных» (далее – Федеральный закон от 27.07.2006 № 152-ФЗ), при предоставлении АНО «МЭЦ» в соответствии с Положением о порядке предоставления Услуги «Организация образовательного курса «Английский язык для внешнеэкономической деятельности». Мне известно, что предоставленные мною персональные данные будут подвергнуты обработке, предусмотренной Федеральным законом от 27.07.2006 № 152-ФЗ, при этом публикация моих персональных данных будет произведена АНО «МЭЦ» в соответствии с действующим законодательством. Мне известно, что настоящее согласие действует бессрочно. В случае отзыва согласия на обработку персональных данных, АНО «МЭЦ» вправе продолжить обработку персональных данных без моего согласия в соответствии с частью 2 статьи 9, пунктом 4 части 1 статьи 6 Федерального закона от 27.07.2006 № 152-ФЗ.',
            outerId: null,
            outerName: null,
            fileFormats: null,
            fileSizeMaxByte: 0,
          },
          visibility: true,
          isUserFill: true,
          readOnly: false,
          measureServiceParamValueGroup: null,
          stage: {
            order: 2,
            name: '3',
            description: 'Заверения и согласия',
            group: null,
          },
          inputMask: null,
        },
      ],
    },
    {
      id: 122,
      name: 'Документы',
      fields: [
        {
          name: 'Отчет о финансовых результатах за 2 (Два) последних финансовых года и 2 (Два) последних налоговых периода , а в случае если продолжительность регистрации Заявителя менее 2 (Двух) лет, - с момента регистрации Заявителя, с отметкой налогового органа или с приложением копий уведомлений, подтверждающих направление документов в налоговый орган в виде почтового отправления с описями вложений, или с приложением копий извещений о вводе сведений, подтверждающих направление документов в налоговый орган в электронной форме (форма 2 бухгалтерского баланса)',
          description: null,
          parameterInApi: 'p8297118',
          fieldType: {
            id: 2416,
            name: 'Файлы',
            code: null,
            dictionaries: [],
          },
          required: true,
          signatureRequired: true,
          inner: false,
          url: null,
          signatures: [],
          maxSignaturesCount: 1,
          digitalStorageType: {
            name: 'Отчет о финансовых результатах за 2 (Два) последних финансовых года и 2 (Два) последних налоговых периода , а в случае если продолжительность регистрации Заявителя менее 2 (Двух) лет, - с момента регистрации Заявителя, с отметкой налогового органа или с приложением копий уведомлений, подтверждающих направление документов в налоговый орган в виде почтового отправления с описями вложений, или с приложением копий извещений о вводе сведений, подтверждающих направление документов в налоговый орган в электронной форме (форма 2 бухгалтерского баланса)',
            outerId: null,
            outerName: null,
            fileFormats: null,
            fileSizeMaxByte: 0,
          },
          visibility: true,
          isUserFill: true,
          readOnly: false,
          measureServiceParamValueGroup: null,
          stage: {
            order: 3,
            name: '4',
            description: 'Документы',
            group: null,
          },
          inputMask: null,
        },
      ],
    },
  ],
  textarea: [
    {
      id: 13,
      title: 'Оставьте отзыв об услуге',
    },
  ],
};
