export enum RoutePaths {
  ALL = '*',
  PROFILE = '/',
  BASE = '/',
  REPRESENTATIVE_PROFILE = '/profile/representative',
  TESTROUTER = '/testrouter',
  REQUEST_DETAILS = '/request/details',
  REQUEST_DETAIL = '/request/details/:requestId',
  REQUESTS = '/requests',
  REQUEST = '/requests/:requestId',
  SERVICES = '/services',
  SERVICE = '/services/:serviceId',
  EXPORTS = '/exports',
  EVENTS = '/events',
  NOTIFICATIONS = '/notifications',
  SETTINGS = '/settings',
  LOGIN = '/login',
  CALLBACK = '/callback',
  EXIT = '/exit',
  LOGOUT = '/logout',
  TEST_PAGE = '/test',
}
